ExamApp/Models/SeriesExam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamApp.Models
{
    public class SeriesExam
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Status { get; set; }

        public int? SelectedExamId { get; set; }
        public Exam SelectedExam { get; set; }

       
        public int ClassRoomId { get; set; }
        public ClassRoom ClassRoom { get; set; }

        public List<SeriesExamItem> SeriesExamItems { get; set; }
    }
}

ExamApp/Controllers/SeriesExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamApp.Data;
using ExamApp.Models;
using Microsoft.AspNetCore.Identity;
using ExamApp.Models.Common.Authentication;

namespace ExamApp.Controllers
{
    public class SeriesExamsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SeriesExamsController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }
      
        // GET: SeriesExams
        public async Task<IActionResult> Index()
        {
            var loggedInUser = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            var teacher = await _context.Teachers.Where(m => m.ApplicationUserId == loggedInUser.Id).FirstOrDefaultAsync();



            var applicationDbContext = _context.SeriesExams
                .Include(s => s.SelectedExam)
                .Include(s => s.ClassRoom)
                .Include(s => s.SeriesExamItems)
                .ThenInclude(s => s.Exam)
                .ThenInclude(s => s.ClassRoom)
                .ThenInclude(s => s.Course)
                .Include(s => s.ClassRoom.Course)
                .Where(m => m.ClassRoom.AcademicSession.Status == 1 && m.ClassRoom.AcademicSession.InstitutionId == loggedInUser.InstitutionId && m.ClassRoom.Teacher.ApplicationUser.Id == loggedInUser.Id);
            return View(await applicationDbContext.ToListAsync());
        }



        // GET: SeriesExams/Create
        public async Task<IActionResult> Create()
        {
            var loggedInUser = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            ViewData["ClassRoomId"] = await _context.ClassRooms
                .Include(m => m.Course)
                .Include(m => m.Section)
                .Where(m => m.Teacher.ApplicationUserId == loggedInUser.Id).ToListAsync();
            return View();
        }

        // POST: SeriesExams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SeriesExam seriesExam)
        {


            seriesExam.Status = 0;

            if (ModelState.IsValid)
            {
                _context.Add(seriesExam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // ViewData["AcademicSessionId"] = new SelectList(_context.AcademicSessions, "Id", "Id", seriesExam.AcademicSessionId);
            return View(seriesExam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSelectedExam(SeriesExam seriesExam)
        {
            var seriesExamTemp = await _context.SeriesExams.Where(m => m.Id == seriesExam.Id).FirstOrDefaultAsync();

            seriesExamTemp.SelectedExamId = seriesExam.SelectedExamId;
                _context.Update(seriesExamTemp);
                await _context.SaveChangesAsync();
            return RedirectToAction("AddExams", new { id = seriesExam.Id });
        }


        public async Task<IActionResult> FinalizeSeriesExam(int id)
        {
            var seriesExam = await _context.SeriesExams
                .Include(m=>m.SeriesExamItems)
                .ThenInclude(m=>m.Exam)
                .Where(m => m.Id == id)
                .FirstOrDefaultAsync();

            foreach (var item in seriesExam.SeriesExamItems)
            {
                if (item.ExamId!= seriesExam.SelectedExamId)
                {
                    var tempExam = await _context.Exams.Where(m => m.Id == item.ExamId).FirstOrDefaultAsync();
                    tempExam.IsNotCountable = true;
                    _context.Update(tempExam);
                    await _context.SaveChangesAsync();
                }

            }
            seriesExam.Status = 1;
            _context.Update(seriesExam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: SeriesExams/Edit/5
        public async Task<IActionResult> AddExams(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seriesExam = await _context.SeriesExams
                .Include(c => c.ClassRoom.Course)
                .Include(c => c.ClassRoom.Section)
                .Include(c => c.ClassRoom.Course)
                .Include(c => c.ClassRoom)
                .Include(c => c.SelectedExam)
                .Include(c => c.SeriesExamItems)
                .ThenInclude(c => c.Exam)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seriesExam == null)
            {
                return NotFound();
            }
            if (seriesExam.Status!=0)
            {
                return NotFound();
            }

            var exams = await _context.Exams
                .Where(m => m.ClassRoomId == id)
                .ToListAsync();
            
            foreach (var seriesTempExam in seriesExam.SeriesExamItems)
            {
               
                    exams.Remove(seriesTempExam.Exam);
               
            }
            
            ViewData["Exam"] = exams;

            return View(seriesExam);
        }



        [HttpPost]
        public async Task<JsonResult> AddExamToSeries(int examId, int seriesExamId)
        {


            SeriesExamItem seriesExamItem = new SeriesExamItem();
            seriesExamItem.ExamId = examId;
            seriesExamItem.SeriesExamId = seriesExamId;
            _context.Add(seriesExamItem);
            await _context.SaveChangesAsync();
            return Json(true);

        }
        [HttpPost]
        public async Task<JsonResult> GetExamById(int examId)
        {

            var exam = await _context.Exams.Where(m => m.Id == examId).FirstOrDefaultAsync();

            return Json(exam);

        }

        [HttpPost]
        public async Task<JsonResult> DeleteExamFromSeries( int seriesExamItemId)
        {

            var seriesExamItem = await _context.SeriesExamItems.Where(m => m.Id == seriesExamItemId).FirstOrDefaultAsync();
            _context.Remove(seriesExamItem);
            await _context.SaveChangesAsync();
            return Json(true);

        }


        // GET: SeriesExams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seriesExam = await _context.SeriesExams
                .Include(s => s.ClassRoom.AcademicSession)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seriesExam == null)
            {
                return NotFound();
            }

            return View(seriesExam);
        }

        // POST: SeriesExams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seriesExam = await _context.SeriesExams.FindAsync(id);
            _context.SeriesExams.Remove(seriesExam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SeriesExamExists(int id)
        {
            return _context.SeriesExams.Any(e => e.Id == id);
        }
    }
}

ExamApp/Views/SeriesExams/AddExams.cshtml
@model ExamApp.Models.SeriesExam


@{
    ViewData["Title"] = "Add Exams";
}

@section Css {
    <link asp-append-version="true" type="text/css" rel="stylesheet" href="~/vendor/select2/select2.min.css" />
}

@section Sole {
    <style>
        .select2-container .select2-selection {
            padding: 7px 12px 4px;
            height: 40px;
            font-size: .9125rem;
            background: #fff url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAT9JREFUeNrs100KglAQB/AxXBp0A93UNk+QrosO0CJo1SK6QRARdINo0TWitt3D7mCLOkBvqgcVan5M9C+czQN19Mc8x/c0KCbCMPTVsKcvRyXhnEsAkQS00YFuCcwLVA3iqKGGXEGHQCIO6KMDbXRgOcW5gaqDXQKKCvL0xgHhK9j86QoGwYFOp3PmB3EO5378Hez1BzQcjTMh+VrO4dxCwPsmNTFm08m1EmmRGsc5nFu0gm87uNtpp0a+4jj348C0SAlcFNBLm5iElMJxGC/v4DHrPnCz3dFsvqBGo07r1fJ6TAr3BFQ4hh3z3OQRqT9FEjgOU2IF0RBG6k6XwIkBNbJqWbetkNcSW0lMySVOEhbVxVC7mCigDwu8/2YScgXhgT46sFlOcUGgCwtE+82MqiA80EEHemUF/xl4EWAAT0mXtdDaAKkAAAAASUVORK5CYII=') no-repeat right 0px center;
        }
    </style>
}

<div class="container-fluid mt-4">
    <div class="card mb-4 animated fadeIn">
        <div class="card-header p-3">
            <div class="row align-items-center">
                <div class="col col-md-10">

                    <h3 class="mb-0 skewed skewed-yellow text-dark d-inline-block text-uppercase ls-1">Course : @Model.ClassRoom.Course.Name </h3>

                    <h3 class="mb-0 skewed skewed-blue text-dark d-inline-block text-uppercase ls-1">Section : @Model.ClassRoom.Section.FullName </h3>
                    <h3 class="mb-0 skewed skewed-green text-dark d-inline-block text-uppercase ls-1">Series Exam Name : @Model.Name </h3>
                </div>
                <div class="col-md-2 text-right">
                    <a asp-action="Index" class="btn btn-back">Back</a>
                    <input asp-for="Id" type="hidden" id="seriesExamId" class="seriesExamId">
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <form asp-action="AddSelectedExam">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label text-dark ls-1 text-uppercase">Class Room</label>
                            <input asp-for="Id" type="hidden" id="seriesExamId" class="seriesExamId">
                            <select asp-for="SelectedExamId" class="form-control" data-toggle="select" asp->
                                @foreach (var exam in Model.SeriesExamItems)
                                {

                                    if (Model.SelectedExamId == exam.Id)
                                    {
                                        <option selected value="@exam.Exam.Id">@exam.Exam.Name</option>
                                    }
                                    else
                                    {
                                        <option value="@exam.Exam.Id">@exam.Exam.Name</option>
                                    }

                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group align-text-bottom">
                            <label class="form-control-label text-dark ls-1 text-uppercase">Save Exam</label>
                            <input type="submit" value="Save" class="form-control btn btn-primary" />
                        </div>
                    </div>

                </div>
            </form>
            <div class="table-responsive">
                <table class="table align-items-center table-hover table-striped table-bordered" id="main_table">
                    <thead class="thead-light">
                        <tr>

                            <th class="text-center">Exam Name</th>
                            <th class="text-center">Exam Topic</th>
                            <th class="text-center">Action</th>

                        </tr>
                    </thead>
                    <tbody id="table_body" class="table_body">
                        @if (Model.SeriesExamItems.Count != 0)
                        {
                            @foreach (var seriesExamItem in Model.SeriesExamItems)
                            {
                                bool selectedCheck = false;

                                <tr>
                                    <td class="p-0">
                                        <input type="hidden" id="seriesExamItemId" class="seriesExamItemId" value="@seriesExamItem.Id">
                                        <select class="form-control examId js-single border-0 border-radius-0" data-toggle="select" disabled>
                                            @foreach (var exam in ViewBag.Exam)
                                            {
                                                if (exam.Id != seriesExamItem.ExamId)
                                                {
                                                    <option value="@exam.Id">@exam.Name</option>
                                                }


                                            }

                                            <option selected value="@seriesExamItem.Exam.Id">@seriesExamItem.Exam.Name</option>
                                        </select>

                                    </td>





                                    @if (Model.SelectedExamId == seriesExamItem.Exam.Id)
                                    {
                                        selectedCheck = true;
                                        <td class="p-0 bg-green">
                                            <input class="form-control border-0 border-radius-0 text-center examName" readonly type="text" value="@seriesExamItem.Exam.Topic (Selected)" />
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="p-0">
                                            <input class="form-control border-0 border-radius-0 text-center examName" readonly type="text" value=" @seriesExamItem.Exam.Topic" />
                                        </td>
                                    }





                                    <td class="text-center align-middle p-2">
                                        <div class="btn-group">
                                            <input class="btn btn-success btn-sm save_button mr-0" type="button" disabled name="save_button" id="save_button" value="Saved" />

                                            @if (!selectedCheck)
                                            {
                                                <input class="btn btn-danger btn-sm delete_button " type="button" name="delete_button" id="delete_button" value="Delete" />
                                            }



                                        </div>


                                    </td>


                                </tr>
                            }
                        }


                        <tr>
                            <td class="p-0">
                                <select class="form-control examId js-single border-0 border-radius-0" data-toggle="select">
                                    <option selected value="" disabled>Select</option>
                                    @foreach (var exam in ViewBag.Exam)
                                    {
                                        <option value="@exam.Id">@exam.Name</option>
                                    }

                                </select>
                            </td>
                            <td class="p-0">
                                <input class="form-control border-0 border-radius-0 text-center examName" readonly type="text" value="" />

                            </td>
                            <td class="text-center align-middle p-2">
                                <div class="btn-group">
                                    <input class="btn btn-success btn-sm save_button mr-0" type="button" name="save_button" id="save_button" value="Save" />

                                </div>

                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            @if (Model.Status == 0 && Model.SeriesExamItems.Count != 0)
            {
                <div class="col-12">
                    <div class="text-center">
                        <a class="btn btn-success mt-3 finalizeButton"  id="finalizeButton" asp-controller="SeriesExams" asp-action="FinalizeSeriesExam" asp-route-id="@Model.Id">Finalize</a>
                      
                    </div>
                </div>
            }




        </div>
    </div>
</div>
@section Scripts {
    <script asp-append-version="true" type="text/javascript" src="~/vendor/select2/select2.min.js"></script>
    <script>

        $(document).ready(function () {
            $('.save_button').on('click', function () {
                 var row = $(this).closest('tr');
                var examId = row.find('.examId').val();
                var seriesExamId = $('#seriesExamId').val();

                if (examId == "" || examId == null) {
                    $.notify({

                        title: 'Prompt!',
                        icon: 'fa fa-times',
                        html: true,
                        message: 'Select Exam Before Saving!'
                        },
                        {
                        type: 'warning',
                        animate: {
                            enter: 'animated fadeInDown'
                        },
                        placement: {
                            from: "top",
                            align: "center"
                        },
                        spacing: 10,
                        z_index: 1031,
                        delay: 1000,
                        template: '<div data-notify="container" class="alert alert-dismissible alert-{0} alert-notify" role="alert"><span class="alert-icon" data-notify="icon"></span> <div class="alert-text"</div> <span class="alert-title" data-notify="title">{1}</span> <span data-notify="message">{2}</span></div><button type="button" class="close" data-notify="dismiss" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>'
                        });
                }

                else {
                    $(this).val('Saved');
                    $(this).attr("disabled", true);
                    var url = '@Url.Action("AddExamToSeries", "SeriesExams")';
                     $.ajax({
                         type: "POST",
                         dataType: 'json',
                         url: url,
                         data: {
                             examId: examId,
                             seriesExamId: seriesExamId,
                         },
                         cache: false,
                         success: function (result) {

                             location.reload();
                         }

                     });

                 }

            });

            $('.examId').on('change', function () {
                var row = $(this).closest('tr');
                var examId = row.find('.examId').val();
                var examName = row.find('.examName');
                 var url = '@Url.Action("GetExamById", "SeriesExams")';
                 $.ajax({
                     type: "POST",
                     dataType: 'json',
                     url: url,
                     data: {
                         examId: examId,
                     },
                     cache: false,
                     success: function (result) {
                         examName.val(result.name);
                     }
                 });

             });
            $('.delete_button').on('click', function () {
                var row = $(this).closest('tr');
                var seriesExamItemId = row.find('.seriesExamItemId').val();
                 var url = '@Url.Action("DeleteExamFromSeries", "SeriesExams")';
                 $.ajax({
                     type: "POST",
                     dataType: 'json',
                     url: url,
                     data: {
                         seriesExamItemId: seriesExamItemId,
                     },
                     cache: false,
                     success: function (result) {
                         location.reload();
                     }
                 });

             });
        });

    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamApp/Views/SeriesExams/Create.cshtml
@model ExamApp.Models.SeriesExam


@{
    ViewData["Title"] = "Series Exam";
}

@section Css {
    <link asp-append-version="true" type="text/css" rel="stylesheet" href="~/vendor/select2/select2.min.css" />
}

@section Sole {
    <style>
        .select2-container .select2-selection {
            padding: 7px 12px 4px;
            height: 40px;
            font-size: .9125rem;
            background: #fff url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAT9JREFUeNrs100KglAQB/AxXBp0A93UNk+QrosO0CJo1SK6QRARdINo0TWitt3D7mCLOkBvqgcVan5M9C+czQN19Mc8x/c0KCbCMPTVsKcvRyXhnEsAkQS00YFuCcwLVA3iqKGGXEGHQCIO6KMDbXRgOcW5gaqDXQKKCvL0xgHhK9j86QoGwYFOp3PmB3EO5378Hez1BzQcjTMh+VrO4dxCwPsmNTFm08m1EmmRGsc5nFu0gm87uNtpp0a+4jj348C0SAlcFNBLm5iElMJxGC/v4DHrPnCz3dFsvqBGo07r1fJ6TAr3BFQ4hh3z3OQRqT9FEjgOU2IF0RBG6k6XwIkBNbJqWbetkNcSW0lMySVOEhbVxVC7mCigDwu8/2YScgXhgT46sFlOcUGgCwtE+82MqiA80EEHemUF/xl4EWAAT0mXtdDaAKkAAAAASUVORK5CYII=') no-repeat right 0px center;
        }
    </style>
}

<div class="container-fluid mt-4">
    <div class="card mb-4 animated fadeIn">
        <div class="card-header p-3">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0 skewed skewed-yellow text-dark d-inline-block text-uppercase ls-1">Series Exam</h3>
                </div>
                <div class="col text-right">
                    <a asp-action="Index" class="btn btn-back">Back</a>
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label text-dark ls-1 text-uppercase">Class Room</label>
                            <select asp-for="ClassRoomId" class="form-control" data-toggle="select" asp->
                                @foreach (var item in ViewBag.CLassRoomId)
                                {
                                    <option value="@item.Id">@item.Course.Code  (@item.Section.FullName)</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-control-label text-dark ls-1 text-uppercase">Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group mb-0">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script asp-append-version="true" type="text/javascript" src="~/vendor/select2/select2.min.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamApp/Views/SeriesExams/Details.cshtml
@*@model ExamApp.Models.SeriesExam

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SeriesExam</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SelectedExamId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SelectedExamId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicSession)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicSession.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

ExamApp/Views/SeriesExams/Index.cshtml
@model IEnumerable<ExamApp.Models.SeriesExam>
@{
    ViewData["Title"] = "Series Exam";
}

@section Css {
    @{await Html.RenderPartialAsync("_DataTableCssPartial");}
}

@section Sole {
    <style>


        .table tr th:last-child {
            width: 50px;
        }

        .table tr th {
            text-align: center;
        }

        @@media screen and (max-width: 991px) {
            .before-table-responsive .col-sm-12 {
                padding: 0;
                margin-left: 1rem;
                margin-right: 1rem
            }
            /*.buttons-pdf,
            .buttons-excel {
                display: none;
            }*/
        }
    </style>
}

<div class="container-fluid mt-4">
    <div class="card animated fadeIn overflow-hidden">
        <div class="card-header p-3">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0 skewed skewed-yellow text-dark d-inline-block text-uppercase ls-1">Series Exam</h3>
                </div>
                <div class="col text-right">
                    <a asp-action="Create" class="btn btn-create">New</a>
                </div>
            </div>
        </div>
        <div class="card-body px-0 pb-2">
            <div class="" id="table_wrapper">

                <table class="table align-items-center  table-striped table-bordered" id="datatable-basic1">
                    <thead class="thead-light">
                        <tr>

                            <th>
                                Name
                            </th>
                            <th>
                                Course
                            </th>
                            <th>
                                Exams
                            </th>

                            <th>
                                Selected
                            </th>


                            <th class="text-center">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.Name
                                </td>

                                <td>
                                    @item.ClassRoom.Course.Name
                                </td>
                                @{
                                    string exams = "No Exams Selected";
                                    if (item.SeriesExamItems.Count != 0)
                                    {
                                        exams = "| ";
                                        foreach (var examItem in item.SeriesExamItems)
                                        {
                                            exams += examItem.Exam.Name + " | ";
                                        }
                                    }
                                }


                                <td>
                                    @exams
                                </td>

                                @if (item.SelectedExam == null)
                                {
                                    <td>
                                        No Exam Selected
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        @item.SelectedExam.Name
                                    </td>
                                }


                                <td class="text-center">
                                    <div class="btn-group">
                                        @if (item.Status == 0)
                                        {
                                            <a class="btn btn-greenyellow btn-sm" asp-action="AddExams" asp-route-id="@item.Id">Add Exams</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success btn-sm" >Finalized</a>
                                        }
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>



            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script asp-append-version="true" type="text/javascript" src="~/vendor/datatable/js/jquery.dataTables.min.js"></script>
    <script asp-append-version="true" type="text/javascript" src="~/vendor/datatable/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#datatable-basic1').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#table_wrapper .col-md-6:eq(0)');
        });
    </script>
    @{await Html.RenderPartialAsync("_DataTablesJsPartial");}
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}